<?php

it('mounts the real forms viewer and builder without a Livewire dependency in the viewer', function (): void {
    visit('/forms')
        ->waitForEvent('networkidle')
        ->wait(1)
        ->assertScript("document.querySelector('[data-daisy-kit-module=forms-viewer]').dataset.daisyKitState === 'ready'", true)
        ->assertScript("document.querySelector('[data-daisy-kit-module=forms-builder]').dataset.daisyKitState === 'ready'", true)
        ->assertScript('typeof window.Livewire === "object"', true)
        ->assertScript('window.Livewire.all().length === 1', true)
        ->assertCount('script[data-update-uri]', 1)
        ->assertScript('document.querySelector("[data-update-uri]").getAttribute("data-update-uri").startsWith(window.location.origin)', true)
        ->assertScript("window.Livewire.all()[0].el.contains(document.querySelector('[data-daisy-kit-module=forms-builder] .daisy-kit-forms-builder-livewire__catalogue button'))", true)
        ->fill('#contributor-profile [data-daisy-kit-module=forms-viewer] input[name=name]', 'Ada Byron')
        ->assertScript("document.querySelector('#contributor-profile [data-daisy-kit-module=forms-viewer] input[name=name]').value === 'Ada Byron'", true)
        ->click('[data-daisy-kit-module=forms-builder] .daisy-kit-forms-builder-livewire__catalogue button:first-child')
        ->wait(2)
        ->assertNoSmoke()
        ->assertSee('Field 9')
        ->click('[data-daisy-kit-module=forms-builder] button[wire\\:click="undo"]')
        ->wait(1)
        ->assertDontSee('Field 9')
        ->click('[data-daisy-kit-module=forms-builder] button[wire\\:click="redo"]')
        ->wait(1)
        ->assertSee('Field 9')
        ->assertNoAccessibilityIssues(1)
        ->assertNoSmoke();
})->group('browser');

it('filters the real package table and retains keyboard focus', function (): void {
    visit('/table')
        ->waitForEvent('networkidle')
        ->wait(1)
        ->type('#contributor-directory [data-daisy-kit-table-filter]', 'Grace')
        ->assertScript("document.activeElement.matches('#contributor-directory [data-daisy-kit-table-filter]')", true)
        ->assertScript("document.querySelector('#contributor-directory [data-daisy-kit-module=table]').dataset.daisyKitState === 'ready'", true)
        ->assertScript("document.querySelector('#filtered-server-result [data-daisy-kit-module=table]').dataset.daisyKitState === 'ready'", true)
        ->assertCount('[data-daisy-kit-module="table"]', 3)
        ->assertCount('#contributor-directory nav[aria-label="Table pagination"]', 1)
        ->assertSee('Grace Hopper')
        ->assertSeeIn('#filtered-server-result', 'Ada Lovelace')
        ->click('#contributor-directory [data-daisy-kit-table-row-select="grace"]')
        ->assertScript("document.querySelector('#contributor-directory [data-daisy-kit-table-row-select=grace]').checked", true)
        ->click('#contributor-directory [data-daisy-kit-table-detail-toggle="grace"]')
        ->assertScript("!document.querySelector('#contributor-directory [data-daisy-kit-table-detail=grace]').hidden", true)
        ->click('#contributor-directory [data-daisy-kit-table-edit="grace:name"]')
        ->fill('#contributor-directory [data-daisy-kit-table-edit-input="grace:name"]', 'Grace Murray Hopper')
        ->click('#contributor-directory [data-daisy-kit-table-edit-save="grace:name"]')
        ->assertSee('Grace Murray Hopper')
        ->assertNoAccessibilityIssues(1)
        ->assertNoSmoke();
})->group('browser');
